version: '3.4'

services:
  patients-management:
    image: patients-management:latest
    restart: unless-stopped
    environment:
      - "POSTGRES_HOST=${POSTGRES_HOST}"
      - "POSTGRES_PORT=${POSTGRES_PORT}"
      - "KEYCLOAK_HOST=${KEYCLOAK_HOST}"
      - "KEYCLOAK_PORT=${KEYCLOAK_PORT}"
      - "LISTEN_PORT=8080"
    ports:
      - "8083:8080"
    depends_on:
      - postgres
      - keycloak
    networks:
      - app-network
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.0
    restart: unless-stopped
    environment:
      - "KC_DB=postgres"
      - "KEYCLOAK_CREATE_ADMIN_USER=true"
      - "KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN_USER}"
      - "KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}"
      - "KC_HOSTNAME=${KEYCLOAK_HOST}"
      - "KC_PORT=8080"
      - "KC_DB_URL=jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"
      - "KC_DB_SCHEMA=${KEYCLOAK_DATABASE_SCHEMA}"
      - "KC_DB_USERNAME=${POSTGRES_USER}"
      - "KC_DB_PASSWORD=${POSTGRES_PASSWORD}"
    command: start-dev --import-realm
    volumes:
      - ./imports:/opt/keycloak/data/import
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - app-network
  postgres:
    image: postgres:16
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - ./db-scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network
    environment:
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_DB=${POSTGRES_DB}"

networks:
  app-network:
