spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:hospital}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    converters:
      preferred-json-mapper: gson
  liquibase:
    change-log: ${LIQUIBASE_CHANGELOG_PATH:classpath:migrations.xml}
    liquibase-schema: patients_management
    database-change-log-lock-table: changeloglock
    database-change-log-table: changelog

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ${KEYCLOAK_CLIENT_ID:patients-management-app}
            authorization-grant-type: authorization_code
            scope: openid
        provider:
          keycloak:
            issuer-uri: http://${KEYCLOAK_HOST:keycloak}:${KEYCLOAK_PORT:8080}/realms/${KEYCLOAK_REALM:PatientsManagementRealm}
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          issuer-uri: http://${KEYCLOAK_HOST:keycloak}:${KEYCLOAK_PORT:8080}/realms/${KEYCLOAK_REALM:PatientsManagementRealm}

server:
  port: ${LISTEN_PORT:8083}

openApi:
  server:
    url: ${OPENAPI_SERVER_URL:http://localhost:8083}
